default_platform(:ios)

platform :ios do
  lane :test do
    xcode_test(
      version: "10.2",
      scheme_name: "HTWDD"
    ) 
  end
end
default_platform(:ios)

platform :ios do
  lane :fly do |options|
    xcode_deploy(
      bump_type: options[:bump_type],
      scheme_name: "HTWDD",
      version: "11.3",
    )
  end
end